### ISSUE TITLE
How can I add haziness to an image without having depth information

### ISSUE THREAD

**Issue by spaul13** [jacobjohn2016/Hazing-and-Dehazing-Project#1]
First of all great project. I have a question how can I add or augment haziness in an image?

I went through the haze.py code but it requires original image as well as depth image (information). I don't have depth information for the image dataset. Can u plz tell me how can I add haziness in the images now?

**Comment by jake1412** [comment]
Hey, @spaul13 unfortunately I couldn't find any way to add haziness without depth information as of now. But if I do find something, I'll keep you posted.

**Comment by jake1412** [comment]
Added a section for creating depth maps from a single image.
